"""complete tables

Revision ID: 063e1c33ccb0
Revises: a94da735a4ae
Create Date: 2023-11-29 16:10:46.843261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063e1c33ccb0'
down_revision: Union[str, None] = 'a94da735a4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_age'), 'users', ['age'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_age'), table_name='users')
    # ### end Alembic commands ###
