"""update to db

Revision ID: 0a9228f3f736
Revises: f0d22026e291
Create Date: 2023-12-06 14:38:54.914186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9228f3f736'
down_revision: Union[str, None] = 'f0d22026e291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hemispheres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('time_of_day', sa.String(), nullable=True),
    sa.Column('creature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creature_id'], ['creatures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hemispheres_id'), 'hemispheres', ['id'], unique=False)
    op.drop_index('ix_hemisphere_id', table_name='hemisphere')
    op.drop_table('hemisphere')
    op.add_column('creatures', sa.Column('hemisphere_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'creatures', 'hemispheres', ['hemisphere_id'], ['id'])
    op.drop_index('ix_users_age', table_name='users')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_users_age', 'users', ['age'], unique=False)
    op.drop_constraint(None, 'creatures', type_='foreignkey')
    op.drop_column('creatures', 'hemisphere_id')
    op.create_table('hemisphere',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_of_day', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('creature_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creature_id'], ['creatures.id'], name='hemisphere_creature_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='hemisphere_pkey')
    )
    op.create_index('ix_hemisphere_id', 'hemisphere', ['id'], unique=False)
    op.drop_index(op.f('ix_hemispheres_id'), table_name='hemispheres')
    op.drop_table('hemispheres')
    # ### end Alembic commands ###
