"""back populate relationship

Revision ID: 287d67b9a3c4
Revises: 063e1c33ccb0
Create Date: 2023-11-29 20:08:08.744121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287d67b9a3c4'
down_revision: Union[str, None] = '063e1c33ccb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
