"""dropped creatured_id from hemisphere

Revision ID: 95bc72b82150
Revises: c614c2c400fa
Create Date: 2023-12-06 22:40:46.494033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95bc72b82150'
down_revision: Union[str, None] = 'c614c2c400fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hemispheres_creature_id_fkey', 'hemispheres', type_='foreignkey')
    op.drop_column('hemispheres', 'creature_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hemispheres', sa.Column('creature_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('hemispheres_creature_id_fkey', 'hemispheres', 'creatures', ['creature_id'], ['id'])
    # ### end Alembic commands ###
