"""complete tables

Revision ID: a94da735a4ae
Revises: 72fb7301a163
Create Date: 2023-11-29 16:01:41.140826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94da735a4ae'
down_revision: Union[str, None] = '72fb7301a163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creature_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creature_types_id'), 'creature_types', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('hemisphere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('time_of_day', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hemisphere_id'), 'hemisphere', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('creatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('shadow_size', sa.String(), nullable=True),
    sa.Column('sell_nook', sa.Integer(), nullable=True),
    sa.Column('hemisphere_id', sa.Integer(), nullable=True),
    sa.Column('creature_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creature_type_id'], ['creature_types.id'], ),
    sa.ForeignKeyConstraint(['hemisphere_id'], ['hemisphere.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creatures_id'), 'creatures', ['id'], unique=False)
    op.create_index(op.f('ix_creatures_name'), 'creatures', ['name'], unique=False)
    op.create_table('user_caught_creatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creature_id', sa.Integer(), nullable=True),
    sa.Column('user_caught_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creature_id'], ['creatures.id'], ),
    sa.ForeignKeyConstraint(['user_caught_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_caught_creatures_id'), 'user_caught_creatures', ['id'], unique=False)
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.drop_index(op.f('ix_user_caught_creatures_id'), table_name='user_caught_creatures')
    op.drop_table('user_caught_creatures')
    op.drop_index(op.f('ix_creatures_name'), table_name='creatures')
    op.drop_index(op.f('ix_creatures_id'), table_name='creatures')
    op.drop_table('creatures')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_hemisphere_id'), table_name='hemisphere')
    op.drop_table('hemisphere')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_creature_types_id'), table_name='creature_types')
    op.drop_table('creature_types')
    # ### end Alembic commands ###
