"""creature to hemisphere MTO

Revision ID: f0d22026e291
Revises: 287d67b9a3c4
Create Date: 2023-11-29 20:51:40.092997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d22026e291'
down_revision: Union[str, None] = '287d67b9a3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('creatures_hemisphere_id_fkey', 'creatures', type_='foreignkey')
    op.drop_column('creatures', 'hemisphere_id')
    op.add_column('hemisphere', sa.Column('creature_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hemisphere', 'creatures', ['creature_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hemisphere', type_='foreignkey')
    op.drop_column('hemisphere', 'creature_id')
    op.add_column('creatures', sa.Column('hemisphere_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('creatures_hemisphere_id_fkey', 'creatures', 'hemisphere', ['hemisphere_id'], ['id'])
    # ### end Alembic commands ###
